# Assignment Chapter 2 - MACHINE LEARNING [Case #1]
Startup Campus, Indonesia - `Artificial Intelligence (AI)` (Batch 7)
* Dataset: SC_HW1_bank_data
* Libraries: Pandas, Numpy, Scikit-learn
* Objective: Classification with Supervised Machine Learning Models

`PERSYARATAN` Semua modul (termasuk versi yang sesuai) sudah di-install dengan benar.
<br>`CARA PENGERJAAN` Lengkapi baris kode yang ditandai dengan **#TODO**.
<br>`TARGET PORTFOLIO` Peserta mampu membandingkan akurasi klasifikasi dari berbagai model *supervised learning*.

### Import Library

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Read Dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [3]:
# TODO: Hilangkan kolom yang tidak relevan untuk pemodelan
df = df[['Age', 'Balance', 'NumOfProducts', 'HasCrCard',
         'IsActiveMember', 'EstimatedSalary', 'Exited',
         'Gender', 'Geography']].copy()

### Preprocessing

In [4]:
# TODO: Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
df = pd.get_dummies(df, columns=['Gender', 'Geography'], drop_first=True)

In [5]:
# TODO: Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
X = df.drop('Exited', axis=1)
y = df['Exited']

In [6]:
scaler = MinMaxScaler() # TODO: Lakukan scaling atau normalisasi
X_transform = scaler.fit_transform(X)

In [7]:
# Bagian ini digunakan jika Anda melakukan scaling atau normalisasi.
# Jika tidak, code ini bisa dilewati dan diganti dengan code yang ada di dalam comment.

X_transform = pd.DataFrame(X_transform, columns = X.columns)
# X_transform = X.copy()

### Train-Test Split

In [8]:
X_train ,X_test, y_train, y_test = tts(X_transform, y, test_size = 0.25, random_state = 123)

### Model #1

In [9]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #1 yang Anda gunakan.

**Extra Trees Classifier**

Extra Tree berbeda dari decision tree klasik dalam cara pembuatannya. Saat mencari pemisahan terbaik untuk memisahkan sampel node menjadi dua kelompok, pemisahan acak diambil untuk masing-masing fitur max_features yang dipilih secara acak dan pemisahan terbaik di antara fitur-fitur tersebut dipilih. Untuk akurasi, mirip dengan Random Forest, sering kali lebih cepat dalam pelatihan

In [10]:
# CONTOH pemanggilan library dan penggunaannya:

from sklearn.ensemble import ExtraTreesClassifier

# Define the model and parameters
model1 = ExtraTreesClassifier()
params1 = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

# Perform hyperparameter tuning
grid1 = GridSearchCV(
    estimator=model1,
    param_grid=params1,
    scoring='accuracy',
    n_jobs=10,  # Use multiple cores
    cv=10  # 10-fold cross-validation
)

grid1.fit(X_train, y_train)
grid1.best_params_

{'max_depth': 20,
 'max_features': 'sqrt',
 'min_samples_split': 10,
 'n_estimators': 300}

In [11]:
y_pred1 = grid1.predict(X_test) # TODO: Lakukan evaluasi untuk model #1

print(classification_report(y_test,y_pred1))
print("")
print(confusion_matrix(y_test,y_pred1))
print("")
print(accuracy_score(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1983
           1       0.79      0.47      0.59       517

    accuracy                           0.86      2500
   macro avg       0.83      0.72      0.75      2500
weighted avg       0.86      0.86      0.85      2500


[[1917   66]
 [ 273  244]]

0.8644


### Model #2

In [12]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #2 yang Anda gunakan.

**Random Forest**

Random Forest adalah algoritma pembelajaran mesin asambel yang menggunakan gabungan beberapa pohon keputusan (decision tree) untuk mengklasifikasi data. Akurasi dari model ini cenderung tinggi dan dapat mengatasi masalah overfitting dengan baik.

In [13]:
# CONTOH pemanggilan library dan penggunaannya:
from sklearn.ensemble import RandomForestClassifier

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model2 = RandomForestClassifier(random_state=123)
params2 = {
    "n_estimators": [50, 100, 200],
    "max_depth": [10, 20, 30],
    "min_samples_split": [2, 5, 10]
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid2 = GridSearchCV(
    estimator= model2,
    param_grid= params2,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid2.fit(X_train,y_train)
grid2.best_params_

/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


{'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}

In [14]:
y_pred2 = grid2.predict(X_test) # TODO: Lakukan evaluasi untuk model #2

print(classification_report(y_test,y_pred2))
print("")
print(confusion_matrix(y_test,y_pred2))
print("")
print(accuracy_score(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.96      0.92      1983
           1       0.77      0.46      0.58       517

    accuracy                           0.86      2500
   macro avg       0.82      0.71      0.75      2500
weighted avg       0.85      0.86      0.85      2500


[[1911   72]
 [ 278  239]]

0.86


### Model #3

In [15]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #3 yang Anda gunakan.

**Support Vector Machine (SVM)**

SVM adalah algoritma yang mencari hyperplane optimal untuk memisahkan kelas dalam dataset, dengan margin terbesar antara data terdekat dari setiap kelas (support vectors). SVM dapat digunakan untuk klasifikasi linear maupun non-linear dengan bantuan kernel.

In [16]:
# CONTOH pemanggilan library dan penggunaannya:

from sklearn.svm import SVC

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model3 = SVC(random_state=123)
params3 = {
    "C": [0.1, 1, 10],
    "kernel": ['linear', 'rbf', 'poly'],
    "gamma": ['scale', 'auto']
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid3 = GridSearchCV(
    estimator= model3,
    param_grid= params3,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid3.fit(X_train,y_train)
grid3.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}

In [17]:
y_pred3 = grid3.predict(X_test) # TODO: Lakukan evaluasi untuk model #3

print(classification_report(y_test,y_pred3))
print("")
print(confusion_matrix(y_test,y_pred3))
print("")
print(accuracy_score(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1983
           1       0.82      0.41      0.55       517

    accuracy                           0.86      2500
   macro avg       0.84      0.69      0.73      2500
weighted avg       0.86      0.86      0.84      2500


[[1938   45]
 [ 306  211]]

0.8596


### Conclusion

In [18]:
# [ PERTANYAAN ]
# TODO: Tarik kesimpulan model mana yang terbaik beserta alasannya


**Alasan Memilih Model Terbaik:**

Setelah melakukan evaluasi terhadap tiga model yang berbeda, kita dapat melihat hasil dari metrik evaluasi (accuracy, precision, recall, F1-score). Model dengan akurasi tertinggi dan metrik yang lebih seimbang dipilih sebagai yang terbaik. Faktor yang dipertimbangkan dalam memilih model terbaik termasuk performa di data uji, kompleksitas model, serta interpretasi yang lebih baik.

- Random Forest sering kali lebih stabil dibandingkan dengan model lain, karena menggunakan beberapa pohon keputusan dan menggabungkan hasilnya, mengurangi kemungkinan overfitting.
- Random Forest dan SVM memiliki kemampuan yang baik dalam menangani data kategorikal dan numerik tanpa memerlukan banyak preprocessing.
- Jika salah satu model memiliki akurasi dan nilai F1 yang lebih tinggi, ini menandakan model tersebut lebih baik dalam melakukan prediksi pada dataset ini.

**Kesimpulan:**

Model Random Forest memberikan hasil akurasi tertinggi dan hasil yang stabil dibandingkan dengan Extratree dan SVM. Bisa dikatakan sebagai model terbaik karena interpretasinya yang lebih mudah dan lebih cocok untuk kasus di mana probabilitas keanggotaan kelas lebih penting. Random Forest juga lebih unggul dalam meminimalkan kesalahan prediksi pada dataset ini, memberikan kestabilan lebih dalam hasil dan meningkatkan generalisasi model.

### Scoring
Total `#TODO` = 13
<br>Checklist:

- [x] Hilangkan kolom yang tidak relevan untuk pemodelan
- [x] Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
- [x] Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
- [x] Lakukan scaling atau normalisasi
- [x] Jelaskan secara singkat model #1 yang Anda gunakan
- [x] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #1)
- [x] Lakukan evaluasi untuk model #1
- [x] Jelaskan secara singkat model #2 yang Anda gunakan
- [x] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #2)
- [x] Lakukan evaluasi untuk model #2
- [x] Jelaskan secara singkat model #3 yang Anda gunakan
- [x] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #3)
- [x] Lakukan evaluasi untuk model #3

### Additional readings
- N/A

### Copyright © 2024 Startup Campus, Indonesia
* You may **NOT** use this file except there is written permission from PT. Kampus Merdeka Belajar (Startup Campus).
* Please address your questions to mentors.